language: objective-c
xcode_project: SwiftAA.xcodeproj
xcode_scheme: SwiftAA-iOS
osx_image: xcode9.4
xcode_sdk: iphonesimulator11.3
cache: bundler
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
  - bundle install --without=documentation 
script:
  - xcodebuild clean build test -quiet -project SwiftAA.xcodeproj -scheme SwiftAA-iOS  -sdk iphonesimulator11.3 -destination 'platform=iOS Simulator,OS=11.3.1,name=iPhone 8'
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f TestReports/cobertura.xml -X xcodeplist

