language: objective-c
xcode_project: SwiftAA.xcodeproj
xcode_scheme: SwiftAA-iOS
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
cache: bundler
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
  - bundle install --without=documentation 
script:
  - xcodebuild clean build test -quiet -project SwiftAA.xcodeproj -scheme SwiftAA-iOS  -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,OS=12.0,name=iPhone XS'
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f TestReports/cobertura.xml -X coveragepy -X gcov -X xcode -X fix

